# Use the official .NET 8.0 runtime as a base image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Use the SDK image for building the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["MedicalLabApi.csproj", "./"]
RUN dotnet restore "./MedicalLabApi.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "MedicalLabApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MedicalLabApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MedicalLabApi.dll"]
